spring:
  main:
    banner-mode: off

server:
  port: 7004

solace:
  java:
    host: tcp://localhost:55555
    msg-vpn: default
    client-name: producer
    client-username: producer
    client-password: producer
    api-properties:
      session_name: producer_session

logging:
  level:
    root: INFO
    com.solacesystems.jcsmp.*: ERROR
