version: '3.8'

networks:
  spring_demos:
    name: spring_demos_hibernate
    driver: bridge

volumes:
  pg_one:
    name: spring_demos_hibernate_pg_one
  pg_data_one:
    name: spring_demos_hibernate_pg_data_one
  pg_two:
    name: spring_demos_hibernate_pg_two
  pg_data_two:
    name: spring_demos_hibernate_pg_data_two
  pg_three:
    name: spring_demos_hibernate_pg_three
  pg_data_three:
    name: spring_demos_hibernate_pg_data_three

services:
  db_one:
    container_name: spring_demos_hibernate_one
    hostname: db_one
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - 9002:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_one:/var/lib/postgresql
      - pg_data_one:/var/lib/postgresql/data
    networks:
      - spring_demos
  db_two:
    container_name: spring_demos_hibernate_two
    hostname: db_two
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - 7007:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_two:/var/lib/postgresql
      - pg_data_two:/var/lib/postgresql/data
    networks:
      - spring_demos
  db_three:
    container_name: spring_demos_hibernate_three
    hostname: db_three
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - 8004:5432
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_three:/var/lib/postgresql
      - pg_data_three:/var/lib/postgresql/data
    networks:
      - spring_demos
