version: '3.8'

networks:
  spring_demos:
    name: spring_demos_hibernate
    driver: bridge

volumes:
  pg:
    name: spring_demos_hibernate_pg
  pg_data:
    name: spring_demos_hibernate_pg_data

services:
  db:
    container_name: spring_demos_hibernate_pg
    hostname: db
    image: postgres:14.2
    restart: unless-stopped
    ports:
      - 7001:5432
    environment:
      POSTGRES_PASSWORD: spring_demos_hibernate_pg
    volumes:
      - pg:/var/lib/postgresql
      - pg_data:/var/lib/postgresql/data
    networks:
      - spring_demos
