version: '2.1'

networks:
  spring_demos:
    name: spring_demos_solace

volumes:
  solace_primary:
    name: spring_demos_solace_primary
  solace_backup:
    name: spring_demos_solace_backup
  solace_monitoring:
    name: spring_demos_solace_monitoring
  haproxy:
    name: spring_demos_solace_haproxy

x-environment:
  &default-environment
  username_admin_globalaccesslevel: admin
  username_admin_password: ${ADMIN_PASSWORD:-admin}
  system_scaling_maxconnectioncount: 100
  redundancy_enable: "yes"
  redundancy_group_password: topsecret
  redundancy_group_node_primary_connectvia: primary
  redundancy_group_node_primary_nodetype: message_routing
  redundancy_group_node_backup_connectvia: backup
  redundancy_group_node_backup_nodetype: message_routing
  redundancy_group_node_monitoring_connectvia: monitoring
  redundancy_group_node_monitoring_nodetype: monitoring

x-common:
  &default-common
  image: solace/solace-pubsub-standard:9.13.1.38
  shm_size: 1g
  ulimits:
    core: 1
    nofile:
      soft: 2448
      hard: 38048
  networks:
    - spring_demos

services:
  primary:
    container_name: spring_demos_solace_primary
    hostname: primary
    restart: unless-stopped
    ports:
      - 212:2222
    environment:
      <<: *default-environment
      routername: primary
      configsync_enable: "yes"
      redundancy_matelink_connectvia: backup
      redundancy_activestandbyrole: primary
      service_semp_tlsport: 1943
    <<: *default-common
    volumes:
      - solace_primary:/var/lib/solace

  backup:
    container_name: spring_demos_solace_backup
    hostname: backup
    restart: unless-stopped
    ports:
      - 312:2222
    environment:
      <<: *default-environment
      routername: backup
      configsync_enable: "yes"
      redundancy_matelink_connectvia: primary
      redundancy_activestandbyrole: backup
      service_semp_tlsport: 1943
    <<: *default-common
    volumes:
      - solace_backup:/var/lib/solace

  monitoring:
    container_name: spring_demos_solace_monitoring
    hostname: monitoring
    restart: unless-stopped
    ports:
      - 412:2222
    environment:
      <<: *default-environment
      routername: monitoring
      nodetype: monitoring
      service_semp_tlsport: 1943
    <<: *default-common
    volumes:
      - solace_monitoring:/var/lib/solace

  lb:
    container_name: spring_demos_solace_lb
    restart: unless-stopped
    image: haproxy:2.3
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-admin}
    volumes:
      - ./assertMaster.perl:/assertMaster.perl
      - haproxy:/usr/local/etc/haproxy
    entrypoint:
      - /bin/bash
      - -c
      - perl /assertMaster.perl
    ports:
      - 7011:8080
      - 8008:8008
      - 1443:1443
      - 1943:1943
      - 1883:1883
      - 5671:5671
      - 5672:5672
      - 8000:8000
      - 8443:8443
      - 8883:8883
      - 9000:9000
      - 9443:9443
      - 55555:55555
      - 55003:55003
      - 55443:55443
      - 1936:1936
    networks:
      - spring_demos
