version: '3.8'

networks:
  spring_demos:
    name: spring_demos_sonarqube
    driver: bridge

volumes:
  sonarqube_data:
    name: spring_demos_sonarqube_data
  sonarqube_extensions:
    name: spring_demos_sonarqube_extensions
  sonarqube_logs:
    name: spring_demos_sonarqube_logs
  pg:
    name: spring_demos_sonarqube_pg
  pg_data:
    name: spring_demos_sonarqube_pg_data

services:
  db:
    container_name: spring_demos_sonarqube_pg
    hostname: db
    image: postgres:14.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - pg:/var/lib/postgresql
      - pg_data:/var/lib/postgresql/data
    networks:
      - spring_demos
  web:
    container_name: spring_demos_sonarqube_web
    image: sonarqube:lts-community
    restart: unless-stopped
    ports:
      - 19000:9000
      - 19092:9092
    environment:
      TZ: Asia/Tashkent
      ES_JAVA_HOME: /opt/java/openjdk
    volumes:
      - ./sonar.properties:/opt/sonarqube/conf/sonar.properties
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - spring_demos
    depends_on:
      - db
