spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: false
      maximum-pool-size: 3
  jpa:
    show-sql: false
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 1000
        order_updates: true
        batch_versioned_data: true
        session:
          events.log.LOG_QUERIES_SLOWER_THAN_MS: 10
  flyway:
    enabled: false

server:
  port: 9001

logging:
  level.org.hibernate.SQL: INFO
  level.org.hibernate.SQL_SLOW: TRACE
  level.org.hibernate.type.descriptor.sql.BasicBinder: INFO
