spring:
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    name: consumer_one_pg
    url: jdbc:postgresql://localhost:7007/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: false
      maximum-pool-size: 6
  jpa:
    show-sql: false
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/versions
    url: jdbc:postgresql://localhost:7007/postgres
    user: postgres
    password: postgres
    schemas: postgres
  redis:
    database: 1
    host: localhost
    port: 7006
    username: default
    password: redis
    connect-timeout: 5000

server:
  port: 7005

solace:
  java:
    host: tcp://localhost:55555
    msg-vpn: default
    client-name: consumer_one
    client-username: consumer_one
    client-password: consumer_one
    api-properties:
      session_name: consumer_one_session

logging:
  level:
    root: ERROR
    com.solacesystems.jcsmp.*: ERROR
    org.hibernate.*: ERROR
    org.springframework.cache: ERROR
    com.downvoteit.*: INFO

