spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:postgresql://localhost:7007/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: false
      maximum-pool-size: 3
  jpa:
    show-sql: false
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 1000
        order_updates: true
        batch_versioned_data: true
        session:
          events.log.LOG_QUERIES_SLOWER_THAN_MS: 10
  flyway:
    enabled: true
    locations: classpath:db/versions
    url: jdbc:postgresql://localhost:7007/postgres
    user: postgres
    password: postgres
    schemas: postgres

server:
  port: 7005

solace:
  java:
    host: tcp://localhost:55555
    msg-vpn: default
    client-username: consumer_one
    client-password: consumer_one

logging:
  level:
    root: INFO
    com.solacesystems.jcsmp.*: ERROR
    org.hibernate.*: ERROR
