spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server:
  port: 7002

solace:
  jms:
    host: smf://localhost:55555
    msgVpn: default
    clientUsername: default
    clientPassword: default

queues:
  name: jms-queue
