spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - com.zaxxer.hikari.HikariDataSource

server:
  port: 7004

solace:
  java:
    host: tcp://localhost:55555
    msg-vpn: default
    client-username: default
    client-password: default
  jms:
    host: smf://localhost:55555
    msgVpn: default
    clientUsername: default
    clientPassword: default
