spring:
  main:
    banner-mode: off
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.solr.SolrAutoConfiguration, org.springframework.boot.autoconfigure.task.TaskSchedulingAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:7001/postgres
    username: postgres
    password: spring_demos_hibernate_pg
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: false
      maximum-pool-size: 10
  jpa:
    show-sql: false
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format_sql: true
        jdbc.batch_size: 1000
        order_updates: true
        batch_versioned_data: true
        session:
          events.log.LOG_QUERIES_SLOWER_THAN_MS: 10
  flyway:
    enabled: true
    locations: classpath:db/versions
    url: jdbc:postgresql://localhost:7001/postgres
    user: postgres
    password: spring_demos_hibernate_pg
    schemas: postgres

server:
  port: 7002

logging:
  level.org.hibernate.SQL: INFO
  level.org.hibernate.SQL_SLOW: TRACE
  level.org.hibernate.type.descriptor.sql.BasicBinder: INFO
