spring:
  main:
    banner-mode: off
    log-startup-info: false
  datasource:
    name: consumer_two_pg
    url: jdbc:postgresql://localhost:8004/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-test-query: select 1
      auto-commit: false
      maximum-pool-size: 6
  jpa:
    show-sql: false
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/versions
    url: jdbc:postgresql://localhost:8004/postgres
    user: postgres
    password: postgres
    schemas: postgres

server:
  port: 8003

solace:
  java:
    host: tcp://localhost:55555
    msg-vpn: default
    client-name: consumer_two
    client-username: consumer_two
    client-password: consumer_two
    api-properties:
      session_name: consumer_two_session

logging:
  level:
    root: ERROR
    com.solacesystems.jcsmp.*: ERROR
    org.hibernate.*: ERROR
    com.downvoteit.*: INFO
